# Generated by Django 4.0.3 on 2025-03-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workassignments',
            name='isDone',
            field=models.BooleanField(default=False),
        ),
    ]
